set -g default-terminal "screen-256color"
set -g prefix C-t
bind C-t send-prefix
unbind C-b

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

# Instalar os Plugins (sempre no final)
run '~/.config/tmux/plugins/tpm/tpm'

