#+TITLE: Super Mega Ultra Configuration do Will
#+PROPERTY: header-args:emacs-lisp :tangle yes :results silent :exports code


#+begin_quote
We do what we must, because we can. ---GlaDOS
#+end_quote

* What is this?

Essa é uma tentativa de ter uma configuração do emacs relativamente organizada e documentada.
Para gerar a configuração, utilizar =M-x org-babel-tangle= ou =C-c C-v t=.

* Antes de tudo

** Pacotes necessários

- ~sudo port install emacs-mac-app +imagemagick~
- ~sudo port install coreutils~
- ~sudo port install fish~
- ~sudo port install tmux~

* Configuração

** Early Init

Esta seção irá configurar o =early-init.el=, configuração que carrega antes da interface e dos pacotes. Só colocar configurações aqui se for estritamente necessário.

*** Caminho do Libraries

Por algum motivo a instalação usando o mac-ports não encontra as bibliotecas para que a compilação usando o GCC ocorra. Setamos para o caminho correto.
Ignoramos também os warning e errors da compilação assíncrona dos pacotes com o GCC. Com =silent= eles ainda irão aparecer nos logs.

#+begin_src emacs-lisp :tangle "~/.config/emacs/early-init.el" :eval no

  (setenv "LIBRARY_PATH" (string-join '(
                                        "/opt/local/lib/gcc12/gcc/x86_64-apple-darwin22/12.3.0/"
                                        "/opt/local/lib/gcc12/")
                                      ":"))
  (setq native-comp-async-report-warnings-errors 'silent)

#+end_src

*** Desabilita package.el

#+begin_src emacs-lisp :tangle "~/.config/emacs/early-init.el" :eval no
  (setq package-enable-at-startup nil)
#+end_src



** Configuração Principal

*** Bare init.el

Geramos o =init.el= para carregar a super configuração e iniciamos o servidor no final de tudo.

#+begin_src emacs-lisp :tangle "~/.config/emacs/init.el" :eval no
  (load-file "~/.config/emacs/config.el")
  (server-mode 1)
#+end_src

*** Backups

Colocamos os backups todos em um único lugar para que *se* um dia precisar, fica fácil achar.

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist '(("." . "~/.config/emacs/backups")))
  (with-eval-after-load 'tramp
    (add-to-list 'backup-directory-alist
                 (cons tramp-file-name-regexp nil)))
  (setq delete-old-versions -1)
  (setq version-control t)
  (setq vc-make-backup-files t)
  (setq auto-save-file-name-transforms '((".*" "~/.config/emacs/auto-save-list/" t)))
#+END_SRC

*** Performance

Retirado da documentação do [[https://emacs-lsp.github.io/lsp-mode/page/performance/][lsp-mode]].

#+begin_src emacs-lisp
  (setq gc-cons-threshold 100000000)
  (setq read-process-output-max (* 1024 1024))
#+end_src

*** Instalação e Gerenciamento de Pacotes


**** Compilação

**** straight.el
Conforme documentação, instalamos e inicalizamos o Straight.el com os repositórios na pasta =straight=.

#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src


**** use-package.el

Instalamos o =use-package.el= através do Straight.el

#+begin_src emacs-lisp
  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
  (setq use-package-always-ensure t)
#+end_src

*** Who am I?

#+begin_src emacs-lisp
  (setq user-full-name "Willian Tomaz Nieckarz"
        user-mail-address "willian.nieckarz@icloud.com")
#+end_src

*** UI

**** Sim ou Não

Padroniza ~y~ e ~n~ para tudo.

#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

**** Time, give it back

#+begin_src emacs-lisp
  (display-time-mode t)
#+end_src

**** Colunas na Line Bar

#+begin_src emacs-lisp
  (column-number-mode t)
#+end_src

**** Número das linhas

#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

**** Tamanho do Frame

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist
               '(width . 124)
               '(height . 42))
#+end_src

**** Fonte

[[https://commitmono.com/][Commit Mono]].

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist
               '(font . "CommitMono-16"))
#+end_src

**** Vivendo no tempo dos Punch Cards

[[https://www.ibm.com/ibm/history/history/year_1928.html][Since 1928]]

#+begin_src emacs-lisp
  (setq fill-column 80)
#+end_src

**** Tabs are Evil

#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2)
  (setq indent-line-function 'insert-tab)
#+end_src

**** Tema

***** Modus

[[https://protesilaos.com/emacs/modus-themes][Modus Themes]]

#+begin_src emacs-lisp
  (use-package modus-themes
    :defer t
    :config)
#+end_src

***** Curry On

#+begin_src emacs-lisp
  (use-package curry-on-theme
    :config)
#+end_src


***** Fluc UI
#+begin_src emacs-lisp
  (use-package flucui-themes
    :config (flucui-themes-load-style 'dark))
#+end_src

**** Desabilitar Toolbar e Scrollbar

#+begin_src emacs-lisp
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

**** Desabilitar a tela inicial

#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
#+end_src

*** Diminish

#+begin_src emacs-lisp
  (use-package diminish
    :config (diminish 'auto-fill-function)
    (diminish 'eldoc-mode))
#+end_src

*** Minions

Unifica vários minors-mode em um único lugar.

#+begin_src emacs-lisp
  (use-package minions
    :config (minions-mode 1))
#+end_src

*** Mood Line
#+begin_src emacs-lisp
  (use-package mood-line
    :config
    (mood-line-mode)
    :custom
    (mood-line-format mood-line-format-default-extended))
#+end_src


*** Rainbow Delimiters

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

*** Vertico

Minibuffer vertical ao invés de colunas

#+begin_src emacs-lisp
  (use-package vertico
    :custom
    (vertico-count 12)
    (vertico-resize t)
    (vertico-cycle nil)
    :config
    (vertico-mode))
#+end_src

*** Marginalia

Adiciona anotações no minibuffer

#+begin_src emacs-lisp
  (use-package marginalia
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle))
    :init
    (marginalia-mode))
#+end_src

*** Orderless

Adiciona um "engine" melhor de autocomplete

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

** Configurações Gerais

Pacotes e configurações comuns para programação e edição de texto.

*** Assistente para comandos

**** Which Key

#+begin_src emacs-lisp
  (use-package which-key
    :diminish
    :init (which-key-mode t))
#+end_src

**** Recentf

#+begin_src emacs-lisp
  (use-package recentf
    :custom ((recentf-auto-cleanup 'never)
             (recentf-max-saved-items 25)
             (recentf-max-menu-items 25))
    :config
    (recentf-mode 1))
#+end_src

*** PlantUML

#+begin_src emacs-lisp
  (use-package plantuml-mode
    :custom (plantuml-executable-path "/opt/local/bin/plantuml")
    (plantuml-default-exec-mode 'executable))
#+end_src

*** Ledger
#+begin_src emacs-lisp
  (use-package ledger-mode)
#+end_src

*** Edição em Geral

**** Paredit

Configuramos o Smartparens globalmente e para ignorar os ='=.
#+end_src

*** Edição em Geral

**** Paredit

Configuramos o Smartparens globalmente e para ignorar os ='=.

#+begin_src emacs-lisp
  (use-package paredit
    :hook
    ((emacs-lisp-mode-hook . paredit-mode)
     (lisp-interaction-mode-hook . paredit-mode)
     (ielm-mode-hook . paredit-mode)
     (cider-mode . paredit-mode)
     (cider-repl-mode . paredit-mode)
     (clojure-mode . paredit-mode)
     (lisp-mode-hook . paredit-mode)))
#+end_src

**** AucTex

#+begin_src emacs-lisp
  (use-package auctex
    :config
    (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
          TeX-source-correlate-start-server t)
    (add-hook 'TeX-after-compilation-finished-functions
              #'TeX-revert-document-buffer))
#+end_src

**** CDLatex

#+begin_src emacs-lisp
  (use-package cdlatex
    :hook (LaTeX-mode . turn-on-cdlatex))
#+end_src

**** PDF Tools

#+begin_src emacs-lisp
  (use-package pdf-tools
    :config (pdf-loader-install))
#+end_src

*** Programação

**** Magit
#+begin_src emacs-lisp
  (use-package magit)
#+end_src

**** yaml

#+begin_src emacs-lisp
  (use-package yaml-mode)
#+end_src

**** Fish

#+begin_src emacs-lisp
  (use-package fish-mode)
#+end_src

**** Rest Client

#+begin_src emacs-lisp
  (use-package restclient)
#+end_src

**** NixOS
#+begin_src emacs-lisp
  (use-package nix-mode
    :mode "\\.nix\\'")
#+end_src

***** Babel Rest Client

#+begin_src emacs-lisp
  (use-package ob-restclient
    :after restclient
    :custom (org-babel-do-load-languages
             'org-babel-load-languages
             '((restclient . t))))
#+end_src

**** Clojure

***** Clojure Mode
#+begin_src emacs-lisp
  (use-package clojure-mode
    :hook (clojure-mode . auto-fill-mode))
#+end_src

***** Clojure Refactor

#+begin_src emacs-lisp
  (use-package clj-refactor
    :config (cljr-add-keybindings-with-prefix "C-c C-m")
    :custom (cljr-add-ns-to-blank-clj-files nil)
    :hook (clojure-mode . clj-refactor-mode)
    (clj-refactor-mode . yas-minor-mode))
#+end_src

***** Cider

#+begin_src emacs-lisp
  (use-package cider
    :defer t
    :custom
    (cider-enrich-classpath t))
#+end_src

*** LSP Server

#+begin_src emacs-lisp
  (use-package lsp-mode
    :hook ((clojure-mode . lsp)
           (clojurec-mode . lsp)
           (clojurescript-mode . lsp))
    :custom ((lsp-idle-delay 0.500)
             (lsp-enable-completion-at-point nil)
             (lsp-eldoc-enable-hover nil))
    :config
    (setenv "PATH" (concat
                    "/opt/local/bin" path-separator
                    (getenv "PATH")))
    (dolist (m '(clojure-mode
                 clojurec-mode
                 clojurescript-mode
                 clojurex-mode))
      (add-to-list 'lsp-language-id-configuration `(,m . "clojure"))))
#+end_src


*** LSP UI

#+begin_src emacs-lisp
  (use-package lsp-ui
    :defer t
    :commands lsp-ui-mode)
#+end_src

*** Company Mode

#+begin_src emacs-lisp
  (use-package company
    :config (cider-enable-flex-completion)
    :custom ((tab-always-indent 'complete)
             (company-minimum-prefix-length 1)
             (company-idle-delay 0.0))
    :hook ((cider-repl-mode . company-mode)
           (cider-mode . company-mode))
    :diminish t)
#+end_src


*** Navegação e Arquivos

**** Dired

Usar o ls do pacote coreutils.

#+begin_src emacs-lisp
  (use-package dired
    :straight nil
    :ensure nil
    :config
    ;; Permite que 'a' abra o arquivo.
    (put 'dired-find-alternate-file 'disabled nil)
    :custom
    (dired-listing-switches "-ahl --group-directories-first")
    (insert-directory-program "/opt/local/bin/gls"))
#+end_src

**** Projectile

#+begin_src emacs-lisp
  (use-package projectile
    :config (projectile-mode t)
    :custom (projectile-project-search-path '("~/Development" "~/Projects"))
    :bind-keymap ("M-p" . projectile-command-map))
#+end_src

**** NeoTree
#+begin_src emacs-lisp
  (use-package emacs-neotree
    :straight (emacs-neotree :type git
                             :host github
                             :repo "jaypei/emacs-neotree")
    :custom (neo-theme 'arrow)
    :config (defun neotree-project-dir ()
              "Abre o NeoTree no diretório inicial do Projectile. Retirado da EmacsWiki"
              (interactive)
              (let (project-dir (projectile-project-root))
                (neotree-toggle)
                (if project-dir
                    (if (neo-global--window-exists-p)
                        (progn
                          (neotree-dir project-dir)))
                  (message "Arquivo não aberto pelo Projectile"))))

    :bind (("<f8>" . neotree-toggle)
           ("C-c <f8>" . 'neotree-project-dir)))
#+end_src

**** ag

Pesquisar em arquivos utilizando ~ag~

#+begin_src emacs-lisp
  (use-package ag)
#+end_src


*** Little Axe Functions

Funções feitas no machadinho!

#+begin_src emacs-lisp

  (defun my-add-line-numbers (&optional n)
    "Adiciona números às linhas do arquivo a partir do cursor"
    (interactive)
    (if (equal n nil)
        (add_line_numbers 1))
    (when (not (eobp))
      (progn
        (beginning-of-line 2)
        (insert (number-to-string n) " ")
        (add_line_numbers (+ n 1)))))


  (defun my-toggle-fullscreen ()
    "Coloca em Full Screen (retirado da EmacsWiki)"
    (interactive)
    (set-frame-parameter
     nil 'fullscreen
     (when (not (frame-parameter nil 'fullscreen)) 'fullboth)))

#+end_src
